### PR TITLE
Add next and previous buttons in the occurrence view page #335

### PR DESCRIPTION
**Pull request by sylmorin-gbif**
Add new buttons Next / Previous on the occurrence detail page.

If we reach a page limit, the Next/Previous will trigger a new SolR query (through biocache-service) to continue on the next/previous page.

The "back to result" link will be updated to reflect the current page of the last occurrence seen.

This PR introduce a session object to store:
- the current occurrenceID
- the list of occurrenceIDs of the current page (to avoid triggering a SolR query for each next/previous click)
- the current searchParams to build the "back to result" link

### CODE REVIEW

**Comment by sylmorin-gbif** [comment]
issue335

**Comment by ansell** [comment]
@nickdos What is the history with Session state in `biocache-hubs`? Was there an intentional decision not to use it in the past?

**Comment by nickdos** [comment]
@ansell at one point the app was stateless but the "back to results" button uses session data (from memory), so should be fine to merge this PR. Are there any concerns for load balancing?

**Comment by ansell** [comment]
@nickdos The load balancer has a 1 day "stickiness" setting on user sessions, so that should be fine for cases like this except when we deploy during the day, because the sessions are not persisted in a database currently.

**Comment by nickdos** [comment]
I think we can live with losing the session data on restart - not a big deal for the user.

**Comment by nickdos** [comment]
Thanks @sylmorin-gbif - this is a really nice feature. 

I'm just testing it locally and noticed that if you view the first record, the "previous" button is active and when clicked, it just reloads the current record. I'm thinking it would be better for it to work the same as the results screen, where the "previous" button is hidden or disabled if you are on the first page (same for last record). Would this be hard to do?

**Comment by sylmorin-gbif** [comment]
Hi,

I just added the feature to disable Next or Previous button when we reach the last/first occurrence.

By the way, this dev will also fix a confusing behavior I had lot of time: when you bookmark an occurrence page, if you open it later, after a server restart or in private mode, the "Back to result" button was doing nothing since there was no more "session" object. It was quite confusing.

Now, the button will be hidden if there is no session object.

**Comment by nickdos** [comment]
> I just added the feature to disable Next or Previous button when we reach the last/first occurrence.

Thanks - will test and merge today

> By the way, this dev will also fix a confusing behavior I had lot of time: when you bookmark an occurrence page, if you open it later, after a server restart or in private mode, the "Back to result" button was doing nothing since there was no more "session" object. It was quite confusing.
> 
> Now, the button will be hidden if there is no session object.

Yeah, I was aware of this, so thanks for fixing.

**Comment by nickdos** [comment]
Changes look great ✅

**Pull request merged**
